import glob,os,json,hashlib
# textbook packs: content/topics/<key>.json grouped by course into packs/<sid>-<ui>.json, plus an index compiled into the page
topics={}
for f in sorted(glob.glob('content/topics/*.json')):
    o=json.load(open(f,encoding='utf-8'))
    topics[o['key']]=o
courses={}
for k,o in topics.items():
    sid,ui,_=k.split('-')
    courses.setdefault(sid+'-'+ui,{})[k]=o
os.makedirs('packs',exist_ok=True)
for old in glob.glob('packs/*.json'):
    if os.path.basename(old)[:-5] not in courses: os.remove(old)
index={}
for c,ts in sorted(courses.items()):
    body=json.dumps(ts,ensure_ascii=False,separators=(',',':'),sort_keys=True)
    open('packs/'+c+'.json','w',encoding='utf-8').write(body)
    h=hashlib.sha1(body.encode('utf-8')).hexdigest()[:10]
    for k,o in ts.items(): index[k]={'c':c,'h':h,'n':len(o['kps']),'s':len(o['sections'])}
pack_js='/* ------------------------------------------------------------------ textbook pack index (generated by build.py) */\nconst PACK_INDEX = '+json.dumps(index,sort_keys=True,separators=(',',':'))+';\n'

head=open('src/00-head.html').read()
css=''.join(open(f).read() for f in sorted(glob.glob('src/*.css')))
head=head.replace('</style>', css+'\n</style>',1)
js=pack_js+''.join(open(f).read()+'\n' for f in sorted(glob.glob('src/*.js')))
out=head+"<script>\n(function () {\n'use strict';\n"+js+"})();\n</script>\n"
open('deep-recall.html','w').write(out)
open('main.js','w').write("(function () {\n'use strict';\n"+js+"})();\n")
print(len(out), 'packs:', ', '.join(f'{c} ({len(t)})' for c,t in sorted(courses.items())))
