import pw from '/opt/node22/lib/node_modules/playwright/index.js';
import fs from 'fs';
const { chromium } = pw;
const html = fs.readFileSync('deep-recall.html','utf8');
const probs = fs.readFileSync('ut.js','utf8').match(/const sample = `([\s\S]*?)`;/)[1].replace(/\\\\/g,'\\');
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 400, height: 1000 } });
const errs = [];
page.on('pageerror', e => errs.push(String(e)));
page.on('console', m => { if (m.type()==='error' && !/ERR_TUNNEL|Failed to load/.test(m.text())) errs.push(m.text()); });
await page.route('**/mathjs@13.2.0/**', r => r.fulfill({ path: '/tmp/mj/package/lib/browser/math.js', contentType: 'application/javascript' }));
await page.addInitScript((probs) => {
  const sample = async (input, o) => { o && o.onText && o.onText({text: probs, delta: probs}); return {text: probs, truncated:false}; };
  sample.json = async () => ({questions:[]});
  sample.limits = async () => ({maxPromptBytes: 262144, images:{maxCount:4, maxInputBytes:2e7, mediaTypes:['image/jpeg','image/png']}, tools:{maxCount:8}});
  window.claude = { use: async (n) => n === 'sample' ? sample : null };
}, probs);
fs.writeFileSync('/tmp/claude-0/wrapped.html', `<!doctype html><html><head><meta charset=utf8><meta name=viewport content="width=device-width,initial-scale=1"></head><body>${html}</body></html>`);
await page.context().route('http://dr.test/**', r => { const u = new URL(r.request().url()); const f = u.pathname === '/' ? '/tmp/claude-0/wrapped.html' : process.cwd() + u.pathname; r.fulfill({ path: f, contentType: f.endsWith('.json') ? 'application/json' : 'text/html' }); }); await page.goto('http://dr.test/');
await page.waitForTimeout(1200);
await page.click('[data-arg="mth"]');
await page.click('[data-act="course"][data-arg="1"]');
await page.click('[data-arg="mth-1-4"]');
await page.click('.sheet [data-act="problems"]');
await page.waitForTimeout(800);
await page.fill('#pans', 'cos(x^2)');
await page.keyboard.press('Enter');
await page.waitForTimeout(300);
await page.fill('#pans', '2x cos(x^2)');
await page.waitForTimeout(300);
await page.screenshot({ path: 'shot2.png', fullPage: true });
await page.keyboard.press('Enter');
await page.waitForTimeout(300);
const fbText = await page.locator('.fb-h').first().textContent().catch(()=>'none');
console.log('feedback:', fbText, '| errors:', JSON.stringify(errs));
await browser.close();
